apiVersion: template.app.sealos.io/v1beta1
kind: Template
metadata:
  name: ${{ defaults.app_name }}
spec:
  title: 'Dify'
  url: 'https://cloud.dify.ai'
  readme: 'https://raw.githubusercontent.com/langgenius/dify/main/README.md'
  icon: 'https://avatars.githubusercontent.com/u/127165244?s=48&v=4'
  template_type: inline
  defaults:
    ingress_name:
      # number or string.
      type: string
      value: ${{ random(8) }}
    app_name:
      type: string
      value: dify-${{ random(8) }}
  inputs:
    volume_size:
      description: 'save data size (Gi)'
      # boolean, choice, number, or string.
      type: string
      default: '1'
      required: false


MODE:api
LOG_LEVEL:INFO
SECRET_KEY:sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
CONSOLE_URL:'https://gxiuihzrstsj.cloud.sealos.io:3000'
API_URL:'https://gxiuihzrstsj.cloud.sealos.io:5001'
APP_URL:'https://qiiuslawjjdj.cloud.sealos.io:3000'
MIGRATION_ENABLED:'true'
DB_USERNAME:postgres
DB_PASSWORD:''
DB_HOST:postgresql-postgresql.ns-7otl3mb2.svc
DB_PORT:5432
DB_DATABASE:dify
REDIS_HOST:myredis-redis.ns-7otl3mb2.svc
REDIS_PORT:6379
REDIS_USERNAME:''
REDIS_PASSWORD:''
REDIS_USE_SSL:'false'
REDIS_DB:0
SESSION_TYPE:redis
SESSION_REDIS_HOST:session-redis-redis.ns-7otl3mb2.svc
SESSION_REDIS_PORT:6379
SESSION_REDIS_USERNAME:''
SESSION_REDIS_PASSWORD:''
SESSION_REDIS_USE_SSL:'false'
SESSION_REDIS_DB:2
CELERY_BROKER_URL:redis://:@myredis-redis.ns-7otl3mb2.svc:6379/1
WEB_API_CORS_ALLOW_ORIGINS:'*'
CONSOLE_CORS_ALLOW_ORIGINS:'*'
COOKIE_HTTPONLY:'true'
COOKIE_SAMESITE:'Lax'
COOKIE_SECURE:'false'
STORAGE_TYPE:local
STORAGE_LOCAL_PATH:storage
S3_ENDPOINT:'https://xxx.r2.cloudflarestorage.com'
S3_BUCKET_NAME:'difyai'
S3_ACCESS_KEY:'ak-difyai'
S3_SECRET_KEY:'sk-difyai'
S3_REGION:'us-east-1'
VECTOR_STORE:weaviate
WEAVIATE_ENDPOINT:http://ytsdvhvcydxy.cloud.sealos.io:8080
WEAVIATE_API_KEY:WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
QDRANT_URL:'https://your-qdrant-cluster-url.qdrant.tech/'
QDRANT_API_KEY:'ak-difyai'
SENTRY_DSN:''
SENTRY_TRACES_SAMPLE_RATE:1.0
SENTRY_PROFILES_SAMPLE_RATE:1.0
volumes:
# Mount the storage directory to the container, for storing user files.
- ./volumes/app/storage:/app/api/storage

EDITION:SELF_HOSTED
CONSOLE_URL:''
APP_URL:''
SENTRY_DSN:''