apiVersion: template.app.sealos.io/v1beta1
kind: Template
metadata:
  name: ${{ defaults.app_name }}
spec:
  title: 'Dify'
  url: 'https://cloud.dify.ai'
  readme: 'https://raw.githubusercontent.com/langgenius/dify/main/README.md'
  icon: 'https://avatars.githubusercontent.com/u/127165244?s=48&v=4'
  template_type: inline
  defaults:
    ingress_name:
      # number or string.
      type: string
      value: ${{ random(8) }}
    app_name:
      type: string
      value: dify-${{ random(8) }}
  inputs:
    volume_size:
      description: 'save data size (Gi)'
      # boolean, choice, number, or string.
      type: string
      default: '1'
      required: false
