apiVersion: template.app.sealos.io/v1beta1
kind: Template
metadata:
  name: midjourney-ui
spec:
  title: 'midjourney-ui'
  url: 'https://github.com/topics/midjourney-ui'
  github: 'https://github.com/erictik/midjourney-ui'
  author: 'sealos'
  description: 'Midjourney UI is an open source txt2img UI for AI draw.'
  readme: 'https://raw.githubusercontent.com/erictik/midjourney-ui/main/README.md'
  icon: 'https://avatars.githubusercontent.com/u/108114582?s=96&v=4'
  template_type: inline
  defaults:
    app_host:
      # number or string..
      type: string
      value: ${{ random(8) }}
    app_name:
      type: string
      value: midjourney-ui-${{ random(8) }}
  inputs:
    SALAI_TOKEN:
      description: 'SALAI_TOKEN'
      type: string
      default: ''
      required: false
    SERVER_ID:
      description: 'SERVER_ID'
      type: string
      default: ''
      required: false
    CHANNEL_ID:
      description: 'CHANNEL_ID'
      type: string
      default: ''
      required: false
    HUGGINGFACE_TOKEN:
      description: 'HUGGINGFACE_TOKEN'
      type: string
      default: ''
      required: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: midjourney
  annotations:
    originImageName: erictik/midjourney-ui
    deploy.cloud.sealos.io/minReplicas: '1'
    deploy.cloud.sealos.io/maxReplicas: '1'
  labels:
    cloud.sealos.io/app-deploy-manager: midjourney
    app: midjourney
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: midjourney
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: midjourney
        restartTime: '20230719121929'
    spec:
      containers:
        - name: midjourney
          image: erictik/midjourney-ui
          env:
            - name: SALAI_TOKEN
              value: ${{ inputs.SALAI_TOKEN }}
            - name: SERVER_ID
              value: ${{ inputs.SERVER_ID }}
            - name: CHANNEL_ID
              value: ${{ inputs.CHANNEL_ID }}
            - name: HUGGINGFACE_TOKEN
              value: ${{ inputs.HUGGINGFACE_TOKEN }}
          resources:
            requests:
              cpu: 100m
              memory: 102Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          command: []
          args: []
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          volumeMounts: []
      volumes: []
